language: objective-c
osx_image: xcode9

env:
  global:
    - XCODEPROJECT="TPreventKVC.xcodeproj"
    - FRAMEWORK_SCHEME="TPreventKVC"

  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"           SCHEME="${FRAMEWORK_SCHEME} iOS"      EXAMPLE_NAME=""                               BUILD_EXAMPLE="NO"    POD_LINT="YES"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"      SCHEME="${FRAMEWORK_SCHEME} tvOS"     EXAMPLE_NAME=""                               BUILD_EXAMPLE="NO"    POD_LINT="NO"
    - DESTINATION="arch=x86_64"                     SCHEME="${FRAMEWORK_SCHEME} macOS"    EXAMPLE_NAME="${FRAMEWORK_SCHEME} Example"    BUILD_EXAMPLE="YES"   POD_LINT="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm"  SCHEME="${FRAMEWORK_SCHEME} watchOS"  EXAMPLE_NAME=""                               BUILD_EXAMPLE="NO"    POD_LINT="NO"

script:
    - env
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcpretty --version
    # Build Framework in Debug and Run Tests if specified
    - xcodebuild clean build -project "$XCODEPROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty

    # Build Example in Debug if specified
    - if [ $BUILD_EXAMPLE == "YES" ]; then
        xcodebuild clean build -project "$XCODEPROJECT" -scheme "$EXAMPLE_NAME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty;
      fi

    # Run `pod lib lint` if specified
    - if [ $POD_LINT == "YES" ]; then
        pod lib lint;
      fi
    